name: Build Plugin

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Java Setup
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Unzip
      run: unzip CaveMeetGame_New.zip

    - name: Build
      run: |
        cd CaveMeetGame
        mvn clean package

    - name: Download Link
      uses: actions/upload-artifact@v4
      with:
        name: CaveMeetGame-Plugin
        path: "CaveMeetGame/target/*.jar"
